### ISSUE TITLE
Ask the bot our blog url

### ISSUE THREAD

**Issue by Fausto95** [Fimba-Code/discord-bot#13]
This is pretty simple.

- `!blog:` would reply: `Aqui está o link do nosso blog $link`

NTH

- `!blog:last` would reply `Aqui está o link do nosso ultimo post $link`

**Comment by JoseCage** [comment]
> * `!blog:last` would reply `Aqui está o link do nosso ultimo post $link`

Interesting. But in this case the question is, do you have any idea of how we can get the "latest" post?

**Comment by Fausto95** [comment]
We can use puppeteer and get the first element from the list of the posts in the blog.

**Comment by JoseCage** [comment]
> We can use puppeteer and get the first element from the list of the posts in the blog.

Puppeteer seems like "too big" just to get the last post. I will check his docs

**Comment by Fausto95** [comment]
We could also query the xml file from rss feed parse it and get the last post

**Comment by JoseCage** [comment]
> We could also query the xml file from rss feed parse it and get the last post

This was my first option :smile: :smile:

I'm checking the best option (and small) to handle this.
